"""Event-based, spatially resolved MRI sequence simulation interfaces."""

from .acquisition import (
    AcquisitionDimensions,
    CartesianAcquisition,
    CartesianAcquisitionFrames,
    CartesianAcquisitionVolumes,
    SpiralAcquisition,
    SpectroscopicAcquisition,
    infer_cartesian_acquisition,
    infer_cartesian_acquisition_frames,
    infer_cartesian_acquisition_volumes,
    infer_spectroscopic_acquisition,
    infer_spiral_acquisition,
    make_cartesian_epi,
)
from .compiler import CompiledSequence, SequenceCompiler
from .convergence import (
    DEFAULT_TIMESTEPS_S,
    ConvergenceCriteria,
    SpinProbeEnsemble,
    TimestepConvergencePoint,
    TimestepConvergenceResult,
    default_probe_checkpoints,
    run_timestep_convergence,
)
from .convergence_suite import (
    SequenceConvergenceCase,
    SequenceConvergenceCaseResult,
    SequenceConvergenceSuiteResult,
    make_adiabatic_inversion_case,
    make_bssfp_case,
    make_default_sequence_convergence_cases,
    make_hard_pulse_case,
    make_mprage_case,
    make_slice_selective_case,
    make_spectral_selective_case,
    make_spin_echo_case,
    run_sequence_convergence_suite,
)
from .model import (
    ADCEvent,
    GradientEvent,
    RFEvent,
    SequenceProgram,
    physical_b1_field_arrays,
    physical_sequence_waveforms,
)
from .encoding import EncodingFrame, resolve_encoding_frame
from .flip_angles import (
    VFA_REFERENCE_DOI,
    ernst_angle_deg,
    variable_flip_angle_schedule,
)
from .probe import SequenceProbeResult
from .reference import ReferenceSimulationResult, simulate_reference_sequence
from .result import SequenceSimulationResult
from .spin_sampling import SpinSampling
from .spoiling import (
    SpinGridRecommendation,
    SpoilerTrainAnalysis,
    analyze_adc_moment_train,
    analyze_phase_cycle_train,
    analyze_repeated_spoiler_train,
    recommend_spin_grid,
    recommend_spin_grid_for_phase_train,
)
from .reconstruction import (
    SequenceReconstructionModel,
    ideal_separate,
    load_reconstruction_dataset,
)
from .scanner import (
    ScannerParameters,
    load_scanner_parameters,
    save_scanner_parameters,
)
from .bruker_export import BrukerExportOptions, export_bruker_raw

from .pulseq import (
    PulseqImportError,
    UnsupportedPulseqVersionError,
    load_pulseq,
)
from .pulseq_builders import (
    make_pulseq_bssfp,
    make_pulseq_csi,
    make_pulseq_epi,
    make_pulseq_flash,
    make_pulseq_spiral,
)
from .advanced_bssfp_builders import (
    GAUBATZ_REFERENCE_TITLE,
    GOLDEN_ANGLE_DEG,
    PICCINI_REFERENCE_DOI,
    SKINNER_REFERENCE_DOI,
    WANG_REFERENCE_DOI,
    make_pulseq_me_bssfp,
    make_pulseq_radial_me_bssfp,
    make_pulseq_spectral_selective_bssfp,
    spiral_phyllotaxis_directions,
)

__all__ = [
    "ADCEvent",
    "AcquisitionDimensions",
    "CartesianAcquisition",
    "CartesianAcquisitionFrames",
    "CartesianAcquisitionVolumes",
    "SpiralAcquisition",
    "SpectroscopicAcquisition",
    "CompiledSequence",
    "ConvergenceCriteria",
    "DEFAULT_TIMESTEPS_S",
    "GradientEvent",
    "EncodingFrame",
    "RFEvent",
    "SequenceCompiler",
    "SequenceConvergenceCase",
    "SequenceConvergenceCaseResult",
    "SequenceConvergenceSuiteResult",
    "SequenceProbeResult",
    "SequenceProgram",
    "physical_b1_field_arrays",
    "physical_sequence_waveforms",
    "ScannerParameters",
    "ReferenceSimulationResult",
    "SequenceSimulationResult",
    "SequenceReconstructionModel",
    "SpinProbeEnsemble",
    "SpinSampling",
    "SpinGridRecommendation",
    "SpoilerTrainAnalysis",
    "analyze_adc_moment_train",
    "analyze_phase_cycle_train",
    "analyze_repeated_spoiler_train",
    "recommend_spin_grid",
    "recommend_spin_grid_for_phase_train",
    "TimestepConvergencePoint",
    "TimestepConvergenceResult",
    "VFA_REFERENCE_DOI",
    "default_probe_checkpoints",
    "make_adiabatic_inversion_case",
    "make_bssfp_case",
    "make_default_sequence_convergence_cases",
    "make_hard_pulse_case",
    "make_mprage_case",
    "make_slice_selective_case",
    "make_spectral_selective_case",
    "make_spin_echo_case",
    "run_sequence_convergence_suite",
    "run_timestep_convergence",
    "simulate_reference_sequence",
    "variable_flip_angle_schedule",
    "ernst_angle_deg",
    "BrukerExportOptions",
    "export_bruker_raw",
    "PulseqImportError",
    "UnsupportedPulseqVersionError",
    "infer_cartesian_acquisition",
    "infer_cartesian_acquisition_frames",
    "infer_cartesian_acquisition_volumes",
    "infer_spectroscopic_acquisition",
    "infer_spiral_acquisition",
    "ideal_separate",
    "load_reconstruction_dataset",
    "load_pulseq",
    "load_scanner_parameters",
    "make_cartesian_epi",
    "make_pulseq_bssfp",
    "make_pulseq_csi",
    "make_pulseq_epi",
    "make_pulseq_flash",
    "make_pulseq_me_bssfp",
    "make_pulseq_radial_me_bssfp",
    "make_pulseq_spectral_selective_bssfp",
    "make_pulseq_spiral",
    "spiral_phyllotaxis_directions",
    "GAUBATZ_REFERENCE_TITLE",
    "GOLDEN_ANGLE_DEG",
    "PICCINI_REFERENCE_DOI",
    "SKINNER_REFERENCE_DOI",
    "WANG_REFERENCE_DOI",
    "save_scanner_parameters",
    "resolve_encoding_frame",
]
